/* File: fpylapackmodule.c
 * This file is auto-generated with f2py (version:2.1.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Feb  3 10:26:04 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fpylapack_error;
static PyObject *fpylapack_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef char character;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(fpylapack_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
character_from_pyobj(character* v, PyObject *obj, const char *errmess) {
    if (PyBytes_Check(obj)) {
        /* empty bytes has trailing null, so dereferencing is always safe */
        *v = PyBytes_AS_STRING(obj)[0];
        return 1;
    } else if (PyUnicode_Check(obj)) {
        PyObject* tmp = PyUnicode_AsASCIIString(obj);
        if (tmp != NULL) {
            *v = PyBytes_AS_STRING(tmp)[0];
            Py_DECREF(tmp);
            return 1;
        }
    } else if (PyArray_Check(obj)) {
        PyArrayObject* arr = (PyArrayObject*)obj;
        if (F2PY_ARRAY_IS_CHARACTER_COMPATIBLE(arr)) {
            *v = PyArray_BYTES(arr)[0];
            return 1;
        } else if (F2PY_IS_UNICODE_ARRAY(arr)) {
            // TODO: update when numpy will support 1-byte and
            // 2-byte unicode dtypes
            PyObject* tmp = PyUnicode_FromKindAndData(
                              PyUnicode_4BYTE_KIND,
                              PyArray_BYTES(arr),
                              (PyArray_NBYTES(arr)>0?1:0));
            if (tmp != NULL) {
                if (character_from_pyobj(v, tmp, errmess)) {
                    Py_DECREF(tmp);
                    return 1;
                }
                Py_DECREF(tmp);
            }
        }
    } else if (PySequence_Check(obj)) {
        PyObject* tmp = PySequence_GetItem(obj,0);
        if (tmp != NULL) {
            if (character_from_pyobj(v, tmp, errmess)) {
                Py_DECREF(tmp);
                return 1;
            }
            Py_DECREF(tmp);
        }
    }
    {
        /* TODO: This error (and most other) error handling needs cleaning. */
        char mess[F2PY_MESSAGE_BUFFER_SIZE];
        strcpy(mess, errmess);
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = PyExc_TypeError;
            Py_INCREF(err);
        }
        else {
            Py_INCREF(err);
            PyErr_Clear();
        }
        sprintf(mess + strlen(mess),
                " -- expected str|bytes|sequence-of-str-or-bytes, got ");
        f2py_describe(obj, mess + strlen(mess));
        PyErr_SetString(err, mess);
        Py_DECREF(err);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(dgels,DGELS)(character*,int*,int*,int*,double*,int*,double*,int*,double*,int*,int*);
extern void F_FUNC(dgeqp3,DGEQP3)(int*,int*,double*,int*,int*,double*,double*,int*,int*);
extern void F_FUNC(dorgqr,DORGQR)(int*,int*,int*,double*,int*,double*,double*,int*,int*);
extern void F_FUNC(dormqr,DORMQR)(character*,character*,int*,int*,int*,double*,int*,double*,double*,int*,double*,int*,int*);
extern void F_FUNC(dtptrs,DTPTRS)(character*,character*,character*,int*,int*,double*,double*,int*,int*);
extern void F_FUNC(dtrtrs,DTRTRS)(character*,character*,character*,int*,int*,double*,int*,double*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** dgels ***********************************/
static char doc_f2py_rout_fpylapack_dgels[] = "\
b = dgels(a,b,[trans])\n\nWrapper for ``dgels``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (lda,*)\n"
"b : input rank-2 array('d') with bounds (ldb,*)\n"
"\nOther Parameters\n----------------\n"
"trans : input bytes, optional\n    Default: 'N'\n"
"\nReturns\n-------\n"
"b : rank-2 array('d') with bounds (ldb,*)";
/* extern void F_FUNC(dgels,DGELS)(character*,int*,int*,int*,double*,int*,double*,int*,double*,int*,int*); */
static PyObject *f2py_rout_fpylapack_dgels(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(character*,int*,int*,int*,double*,int*,double*,int*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    character trans = 0;
    PyObject *trans_capi = Py_None;
    int m = 0;
    int n = 0;
    int nrhs = 0;
    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int lda = 0;
    double *b = NULL;
    npy_intp b_Dims[2] = {-1, -1};
    const int b_Rank = 2;
    PyArrayObject *capi_b_as_array = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    int ldb = 0;
    double *work = NULL;
    npy_intp work_Dims[1] = {-1};
    const int work_Rank = 1;
    PyArrayObject *capi_work_as_array = NULL;
    int capi_work_intent = 0;
    int lwork = 0;
    int info = 0;
    static char *capi_kwlist[] = {"a","b","trans",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|O:fpylapack.dgels",\
        capi_kwlist,&a_capi,&b_capi,&trans_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fpylapack.fpylapack.dgels: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable b */
    ;
    capi_b_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "fpylapack.fpylapack.dgels: failed to create array from the 2nd argument `b`";
    capi_b_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,b_Dims,b_Rank,  capi_b_intent,b_capi,capi_errmess);
    if (capi_b_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        b = (double *)(PyArray_DATA(capi_b_as_array));

    /* Processing variable info */
    /* Processing variable m */
    m = shape(a,0);
    /* Processing variable n */
    n = shape(a,1);
    /* Processing variable nrhs */
    nrhs = shape(b,1);
    /* Processing variable lda */
    lda = shape(a,0);
    /* Processing variable ldb */
    ldb = shape(b,0);
    CHECKSCALAR(ldb>=max(m,n),"ldb>=max(m,n)","hidden ldb","dgels:ldb=%d",ldb) {
    /* Processing variable lwork */
    lwork = max(1, min(m, n)+max(min(m, n), nrhs)*2);
    /* Processing variable trans */
    if (trans_capi == Py_None) trans = 'N'; else
        f2py_success = character_from_pyobj(&trans,trans_capi,"fpylapack.dgels() 1st keyword (trans) can't be converted to character");
    if (f2py_success) {
    /* Processing variable work */
    work_Dims[0]=lwork;
    capi_work_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
    const char * capi_errmess = "fpylapack.fpylapack.dgels: failed to create array from the hidden `work`";
    capi_work_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,work_Dims,work_Rank,  capi_work_intent,Py_None,capi_errmess);
    if (capi_work_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        work = (double *)(PyArray_DATA(capi_work_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&trans,&m,&n,&nrhs,a,&lda,b,&ldb,work,&lwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_b_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        Py_XDECREF(capi_work_as_array);
    }  /* if (capi_work_as_array == NULL) ... else of work */
    /* End of cleaning variable work */
    } /*if (f2py_success) of trans*/
    /* End of cleaning variable trans */
    /* End of cleaning variable lwork */
    } /*CHECKSCALAR(ldb>=max(m,n))*/
    /* End of cleaning variable ldb */
    /* End of cleaning variable lda */
    /* End of cleaning variable nrhs */
    /* End of cleaning variable n */
    /* End of cleaning variable m */
    /* End of cleaning variable info */
    }  /* if (capi_b_as_array == NULL) ... else of b */
    /* End of cleaning variable b */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of dgels ********************************/

/*********************************** dgeqp3 ***********************************/
static char doc_f2py_rout_fpylapack_dgeqp3[] = "\
a,jpvt,tau = dgeqp3(a)\n\nWrapper for ``dgeqp3``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (lda,*)\n"
"\nReturns\n-------\n"
"a : rank-2 array('d') with bounds (lda,*)\n"
"jpvt : rank-1 array('i') with bounds (n)\n"
"tau : rank-1 array('d') with bounds (min(n, m))";
/* extern void F_FUNC(dgeqp3,DGEQP3)(int*,int*,double*,int*,int*,double*,double*,int*,int*); */
static PyObject *f2py_rout_fpylapack_dgeqp3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int m = 0;
    int n = 0;
    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int lda = 0;
    int *jpvt = NULL;
    npy_intp jpvt_Dims[1] = {-1};
    const int jpvt_Rank = 1;
    PyArrayObject *capi_jpvt_as_array = NULL;
    int capi_jpvt_intent = 0;
    double *tau = NULL;
    npy_intp tau_Dims[1] = {-1};
    const int tau_Rank = 1;
    PyArrayObject *capi_tau_as_array = NULL;
    int capi_tau_intent = 0;
    double *work = NULL;
    npy_intp work_Dims[1] = {-1};
    const int work_Rank = 1;
    PyArrayObject *capi_work_as_array = NULL;
    int capi_work_intent = 0;
    int lwork = 0;
    int info = 0;
    static char *capi_kwlist[] = {"a",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:fpylapack.dgeqp3",\
        capi_kwlist,&a_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "fpylapack.fpylapack.dgeqp3: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable info */
    /* Processing variable m */
    m = shape(a,0);
    /* Processing variable n */
    n = shape(a,1);
    /* Processing variable lda */
    lda = shape(a,0);
    /* Processing variable jpvt */
    jpvt_Dims[0]=n;
    capi_jpvt_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "fpylapack.fpylapack.dgeqp3: failed to create array from the hidden `jpvt`";
    capi_jpvt_as_array = ndarray_from_pyobj(  NPY_INT,1,jpvt_Dims,jpvt_Rank,  capi_jpvt_intent,Py_None,capi_errmess);
    if (capi_jpvt_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        jpvt = (int *)(PyArray_DATA(capi_jpvt_as_array));

    /* Processing variable tau */
    tau_Dims[0]=min(n, m);
    capi_tau_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "fpylapack.fpylapack.dgeqp3: failed to create array from the hidden `tau`";
    capi_tau_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,tau_Dims,tau_Rank,  capi_tau_intent,Py_None,capi_errmess);
    if (capi_tau_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tau = (double *)(PyArray_DATA(capi_tau_as_array));

    /* Processing variable lwork */
    lwork = 2*n+(n+1)*2;
    /* Processing variable work */
    work_Dims[0]=lwork;
    capi_work_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
    const char * capi_errmess = "fpylapack.fpylapack.dgeqp3: failed to create array from the hidden `work`";
    capi_work_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,work_Dims,work_Rank,  capi_work_intent,Py_None,capi_errmess);
    if (capi_work_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        work = (double *)(PyArray_DATA(capi_work_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&m,&n,a,&lda,jpvt,tau,work,&lwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNN",capi_a_as_array,capi_jpvt_as_array,capi_tau_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        Py_XDECREF(capi_work_as_array);
    }  /* if (capi_work_as_array == NULL) ... else of work */
    /* End of cleaning variable work */
    /* End of cleaning variable lwork */
    }  /* if (capi_tau_as_array == NULL) ... else of tau */
    /* End of cleaning variable tau */
    }  /* if (capi_jpvt_as_array == NULL) ... else of jpvt */
    /* End of cleaning variable jpvt */
    /* End of cleaning variable lda */
    /* End of cleaning variable n */
    /* End of cleaning variable m */
    /* End of cleaning variable info */
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of dgeqp3 *******************************/

/*********************************** dorgqr ***********************************/
static char doc_f2py_rout_fpylapack_dorgqr[] = "\
a = dorgqr(a,tau)\n\nWrapper for ``dorgqr``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (lda,*)\n"
"tau : input rank-1 array('d') with bounds (*)\n"
"\nReturns\n-------\n"
"a : rank-2 array('d') with bounds (lda,*)";
/* extern void F_FUNC(dorgqr,DORGQR)(int*,int*,int*,double*,int*,double*,double*,int*,int*); */
static PyObject *f2py_rout_fpylapack_dorgqr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,int*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int m = 0;
    int n = 0;
    int k = 0;
    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int lda = 0;
    double *tau = NULL;
    npy_intp tau_Dims[1] = {-1};
    const int tau_Rank = 1;
    PyArrayObject *capi_tau_as_array = NULL;
    int capi_tau_intent = 0;
    PyObject *tau_capi = Py_None;
    double *work = NULL;
    npy_intp work_Dims[1] = {-1};
    const int work_Rank = 1;
    PyArrayObject *capi_work_as_array = NULL;
    int capi_work_intent = 0;
    int lwork = 0;
    int info = 0;
    static char *capi_kwlist[] = {"a","tau",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:fpylapack.dorgqr",\
        capi_kwlist,&a_capi,&tau_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "fpylapack.fpylapack.dorgqr: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable tau */
    ;
    capi_tau_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fpylapack.fpylapack.dorgqr: failed to create array from the 2nd argument `tau`";
    capi_tau_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,tau_Dims,tau_Rank,  capi_tau_intent,tau_capi,capi_errmess);
    if (capi_tau_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tau = (double *)(PyArray_DATA(capi_tau_as_array));

    /* Processing variable info */
    /* Processing variable m */
    m = shape(a,0);
    /* Processing variable k */
    k = shape(tau,0);
    /* Processing variable lda */
    lda = shape(a,0);
    /* Processing variable n */
    n = min(shape(a,0), shape(a,1));
    CHECKSCALAR(n>=k,"n>=k","hidden n","dorgqr:n=%d",n) {
    /* Processing variable lwork */
    lwork = n*2;
    /* Processing variable work */
    work_Dims[0]=lwork;
    capi_work_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
    const char * capi_errmess = "fpylapack.fpylapack.dorgqr: failed to create array from the hidden `work`";
    capi_work_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,work_Dims,work_Rank,  capi_work_intent,Py_None,capi_errmess);
    if (capi_work_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        work = (double *)(PyArray_DATA(capi_work_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&m,&n,&k,a,&lda,tau,work,&lwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_a_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        Py_XDECREF(capi_work_as_array);
    }  /* if (capi_work_as_array == NULL) ... else of work */
    /* End of cleaning variable work */
    /* End of cleaning variable lwork */
    } /*CHECKSCALAR(n>=k)*/
    /* End of cleaning variable n */
    /* End of cleaning variable lda */
    /* End of cleaning variable k */
    /* End of cleaning variable m */
    /* End of cleaning variable info */
    if((PyObject *)capi_tau_as_array!=tau_capi) {
        Py_XDECREF(capi_tau_as_array); }
    }  /* if (capi_tau_as_array == NULL) ... else of tau */
    /* End of cleaning variable tau */
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of dorgqr *******************************/

/*********************************** dormqr ***********************************/
static char doc_f2py_rout_fpylapack_dormqr[] = "\
c = dormqr(a,tau,c,[side,trans])\n\nWrapper for ``dormqr``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (lda,*)\n"
"tau : input rank-1 array('d') with bounds (k)\n"
"c : input rank-2 array('d') with bounds (ldc,*)\n"
"\nOther Parameters\n----------------\n"
"side : input bytes, optional\n    Default: 'L'\n"
"trans : input bytes, optional\n    Default: 'N'\n"
"\nReturns\n-------\n"
"c : rank-2 array('d') with bounds (ldc,*)";
/* extern void F_FUNC(dormqr,DORMQR)(character*,character*,int*,int*,int*,double*,int*,double*,double*,int*,double*,int*,int*); */
static PyObject *f2py_rout_fpylapack_dormqr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(character*,character*,int*,int*,int*,double*,int*,double*,double*,int*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    character side = 0;
    PyObject *side_capi = Py_None;
    character trans = 0;
    PyObject *trans_capi = Py_None;
    int m = 0;
    int n = 0;
    int k = 0;
    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int lda = 0;
    double *tau = NULL;
    npy_intp tau_Dims[1] = {-1};
    const int tau_Rank = 1;
    PyArrayObject *capi_tau_as_array = NULL;
    int capi_tau_intent = 0;
    PyObject *tau_capi = Py_None;
    double *c = NULL;
    npy_intp c_Dims[2] = {-1, -1};
    const int c_Rank = 2;
    PyArrayObject *capi_c_as_array = NULL;
    int capi_c_intent = 0;
    PyObject *c_capi = Py_None;
    int ldc = 0;
    double *work = NULL;
    npy_intp work_Dims[1] = {-1};
    const int work_Rank = 1;
    PyArrayObject *capi_work_as_array = NULL;
    int capi_work_intent = 0;
    int lwork = 0;
    int info = 0;
    static char *capi_kwlist[] = {"a","tau","c","side","trans",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|OO:fpylapack.dormqr",\
        capi_kwlist,&a_capi,&tau_capi,&c_capi,&side_capi,&trans_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable side */
    if (side_capi == Py_None) side = 'L'; else
        f2py_success = character_from_pyobj(&side,side_capi,"fpylapack.dormqr() 1st keyword (side) can't be converted to character");
    if (f2py_success) {
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fpylapack.fpylapack.dormqr: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable c */
    ;
    capi_c_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "fpylapack.fpylapack.dormqr: failed to create array from the 3rd argument `c`";
    capi_c_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,c_Dims,c_Rank,  capi_c_intent,c_capi,capi_errmess);
    if (capi_c_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        c = (double *)(PyArray_DATA(capi_c_as_array));

    /* Processing variable info */
    /* Processing variable m */
    m = shape(c,0);
    /* Processing variable n */
    n = shape(c,1);
    /* Processing variable k */
    k = min(shape(a,0), shape(a,1));
    /* Processing variable lda */
    lda = shape(a,0);
    /* Processing variable tau */
    tau_Dims[0]=k;
    capi_tau_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fpylapack.fpylapack.dormqr: failed to create array from the 2nd argument `tau`";
    capi_tau_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,tau_Dims,tau_Rank,  capi_tau_intent,tau_capi,capi_errmess);
    if (capi_tau_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tau = (double *)(PyArray_DATA(capi_tau_as_array));

    /* Processing variable ldc */
    ldc = shape(c,0);
    CHECKSCALAR(m==ldc,"m==ldc","hidden ldc","dormqr:ldc=%d",ldc) {
    /* Processing variable lwork */
    lwork = n*2;
    /* Processing variable trans */
    if (trans_capi == Py_None) trans = 'N'; else
        f2py_success = character_from_pyobj(&trans,trans_capi,"fpylapack.dormqr() 2nd keyword (trans) can't be converted to character");
    if (f2py_success) {
    /* Processing variable work */
    work_Dims[0]=lwork;
    capi_work_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_CACHE;
    const char * capi_errmess = "fpylapack.fpylapack.dormqr: failed to create array from the hidden `work`";
    capi_work_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,work_Dims,work_Rank,  capi_work_intent,Py_None,capi_errmess);
    if (capi_work_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        work = (double *)(PyArray_DATA(capi_work_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&side,&trans,&m,&n,&k,a,&lda,tau,c,&ldc,work,&lwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_c_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
        Py_XDECREF(capi_work_as_array);
    }  /* if (capi_work_as_array == NULL) ... else of work */
    /* End of cleaning variable work */
    } /*if (f2py_success) of trans*/
    /* End of cleaning variable trans */
    /* End of cleaning variable lwork */
    } /*CHECKSCALAR(m==ldc)*/
    /* End of cleaning variable ldc */
    if((PyObject *)capi_tau_as_array!=tau_capi) {
        Py_XDECREF(capi_tau_as_array); }
    }  /* if (capi_tau_as_array == NULL) ... else of tau */
    /* End of cleaning variable tau */
    /* End of cleaning variable lda */
    /* End of cleaning variable k */
    /* End of cleaning variable n */
    /* End of cleaning variable m */
    /* End of cleaning variable info */
    }  /* if (capi_c_as_array == NULL) ... else of c */
    /* End of cleaning variable c */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
    } /*if (f2py_success) of side*/
    /* End of cleaning variable side */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of dormqr *******************************/

/*********************************** dtptrs ***********************************/
static char doc_f2py_rout_fpylapack_dtptrs[] = "\
b = dtptrs(ap,b,[uplo,trans,diag])\n\nWrapper for ``dtptrs``.\
\n\nParameters\n----------\n"
"ap : input rank-1 array('d') with bounds (*)\n"
"b : input rank-2 array('d') with bounds (ldb,nrhs)\n"
"\nOther Parameters\n----------------\n"
"uplo : input bytes, optional\n    Default: 'U'\n"
"trans : input bytes, optional\n    Default: 'N'\n"
"diag : input bytes, optional\n    Default: 'N'\n"
"\nReturns\n-------\n"
"b : rank-2 array('d') with bounds (ldb,nrhs)";
/* extern void F_FUNC(dtptrs,DTPTRS)(character*,character*,character*,int*,int*,double*,double*,int*,int*); */
static PyObject *f2py_rout_fpylapack_dtptrs(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(character*,character*,character*,int*,int*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    character uplo = 0;
    PyObject *uplo_capi = Py_None;
    character trans = 0;
    PyObject *trans_capi = Py_None;
    character diag = 0;
    PyObject *diag_capi = Py_None;
    int n = 0;
    int nrhs = 0;
    double *ap = NULL;
    npy_intp ap_Dims[1] = {-1};
    const int ap_Rank = 1;
    PyArrayObject *capi_ap_as_array = NULL;
    int capi_ap_intent = 0;
    PyObject *ap_capi = Py_None;
    double *b = NULL;
    npy_intp b_Dims[2] = {-1, -1};
    const int b_Rank = 2;
    PyArrayObject *capi_b_as_array = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    int ldb = 0;
    int info = 0;
    static char *capi_kwlist[] = {"ap","b","uplo","trans","diag",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|OOO:fpylapack.dtptrs",\
        capi_kwlist,&ap_capi,&b_capi,&uplo_capi,&trans_capi,&diag_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable uplo */
    if (uplo_capi == Py_None) uplo = 'U'; else
        f2py_success = character_from_pyobj(&uplo,uplo_capi,"fpylapack.dtptrs() 1st keyword (uplo) can't be converted to character");
    if (f2py_success) {
    /* Processing variable ap */
    ;
    capi_ap_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fpylapack.fpylapack.dtptrs: failed to create array from the 1st argument `ap`";
    capi_ap_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,ap_Dims,ap_Rank,  capi_ap_intent,ap_capi,capi_errmess);
    if (capi_ap_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ap = (double *)(PyArray_DATA(capi_ap_as_array));

    /* Processing variable b */
    ;
    capi_b_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "fpylapack.fpylapack.dtptrs: failed to create array from the 2nd argument `b`";
    capi_b_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,b_Dims,b_Rank,  capi_b_intent,b_capi,capi_errmess);
    if (capi_b_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        b = (double *)(PyArray_DATA(capi_b_as_array));

    /* Processing variable info */
    /* Processing variable n */
    n = sqrt(2*shape(ap,0)+0.25)-0.49;
    /* Processing variable nrhs */
    nrhs = shape(b, 1);
    /* Processing variable ldb */
    ldb = shape(b,0);
    /* Processing variable trans */
    if (trans_capi == Py_None) trans = 'N'; else
        f2py_success = character_from_pyobj(&trans,trans_capi,"fpylapack.dtptrs() 2nd keyword (trans) can't be converted to character");
    if (f2py_success) {
    /* Processing variable diag */
    if (diag_capi == Py_None) diag = 'N'; else
        f2py_success = character_from_pyobj(&diag,diag_capi,"fpylapack.dtptrs() 3rd keyword (diag) can't be converted to character");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&uplo,&trans,&diag,&n,&nrhs,ap,b,&ldb,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_b_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of diag*/
    /* End of cleaning variable diag */
    } /*if (f2py_success) of trans*/
    /* End of cleaning variable trans */
    /* End of cleaning variable ldb */
    /* End of cleaning variable nrhs */
    /* End of cleaning variable n */
    /* End of cleaning variable info */
    }  /* if (capi_b_as_array == NULL) ... else of b */
    /* End of cleaning variable b */
    if((PyObject *)capi_ap_as_array!=ap_capi) {
        Py_XDECREF(capi_ap_as_array); }
    }  /* if (capi_ap_as_array == NULL) ... else of ap */
    /* End of cleaning variable ap */
    } /*if (f2py_success) of uplo*/
    /* End of cleaning variable uplo */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of dtptrs *******************************/

/*********************************** dtrtrs ***********************************/
static char doc_f2py_rout_fpylapack_dtrtrs[] = "\
b = dtrtrs(a,b,[uplo,trans,diag])\n\nWrapper for ``dtrtrs``.\
\n\nParameters\n----------\n"
"a : input rank-2 array('d') with bounds (lda,*)\n"
"b : input rank-2 array('d') with bounds (ldb,nrhs)\n"
"\nOther Parameters\n----------------\n"
"uplo : input bytes, optional\n    Default: 'U'\n"
"trans : input bytes, optional\n    Default: 'N'\n"
"diag : input bytes, optional\n    Default: 'N'\n"
"\nReturns\n-------\n"
"b : rank-2 array('d') with bounds (ldb,nrhs)";
/* extern void F_FUNC(dtrtrs,DTRTRS)(character*,character*,character*,int*,int*,double*,int*,double*,int*,int*); */
static PyObject *f2py_rout_fpylapack_dtrtrs(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(character*,character*,character*,int*,int*,double*,int*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    character uplo = 0;
    PyObject *uplo_capi = Py_None;
    character trans = 0;
    PyObject *trans_capi = Py_None;
    character diag = 0;
    PyObject *diag_capi = Py_None;
    int n = 0;
    int nrhs = 0;
    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int lda = 0;
    double *b = NULL;
    npy_intp b_Dims[2] = {-1, -1};
    const int b_Rank = 2;
    PyArrayObject *capi_b_as_array = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    int ldb = 0;
    int info = 0;
    static char *capi_kwlist[] = {"a","b","uplo","trans","diag",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|OOO:fpylapack.dtrtrs",\
        capi_kwlist,&a_capi,&b_capi,&uplo_capi,&trans_capi,&diag_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable uplo */
    if (uplo_capi == Py_None) uplo = 'U'; else
        f2py_success = character_from_pyobj(&uplo,uplo_capi,"fpylapack.dtrtrs() 1st keyword (uplo) can't be converted to character");
    if (f2py_success) {
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "fpylapack.fpylapack.dtrtrs: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable b */
    ;
    capi_b_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
    const char * capi_errmess = "fpylapack.fpylapack.dtrtrs: failed to create array from the 2nd argument `b`";
    capi_b_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,b_Dims,b_Rank,  capi_b_intent,b_capi,capi_errmess);
    if (capi_b_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = fpylapack_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        b = (double *)(PyArray_DATA(capi_b_as_array));

    /* Processing variable info */
    /* Processing variable n */
    n = shape(a,1);
    /* Processing variable nrhs */
    nrhs = shape(b, 1);
    /* Processing variable lda */
    lda = shape(a,0);
    /* Processing variable ldb */
    ldb = shape(b,0);
    /* Processing variable trans */
    if (trans_capi == Py_None) trans = 'N'; else
        f2py_success = character_from_pyobj(&trans,trans_capi,"fpylapack.dtrtrs() 2nd keyword (trans) can't be converted to character");
    if (f2py_success) {
    /* Processing variable diag */
    if (diag_capi == Py_None) diag = 'N'; else
        f2py_success = character_from_pyobj(&diag,diag_capi,"fpylapack.dtrtrs() 3rd keyword (diag) can't be converted to character");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&uplo,&trans,&diag,&n,&nrhs,a,&lda,b,&ldb,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("N",capi_b_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of diag*/
    /* End of cleaning variable diag */
    } /*if (f2py_success) of trans*/
    /* End of cleaning variable trans */
    /* End of cleaning variable ldb */
    /* End of cleaning variable lda */
    /* End of cleaning variable nrhs */
    /* End of cleaning variable n */
    /* End of cleaning variable info */
    }  /* if (capi_b_as_array == NULL) ... else of b */
    /* End of cleaning variable b */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
    } /*if (f2py_success) of uplo*/
    /* End of cleaning variable uplo */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of dtrtrs *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"dgels",-1,{{-1}},0,0,(char *)  F_FUNC(dgels,DGELS),  (f2py_init_func)f2py_rout_fpylapack_dgels,doc_f2py_rout_fpylapack_dgels},
    {"dgeqp3",-1,{{-1}},0,0,(char *)  F_FUNC(dgeqp3,DGEQP3),  (f2py_init_func)f2py_rout_fpylapack_dgeqp3,doc_f2py_rout_fpylapack_dgeqp3},
    {"dorgqr",-1,{{-1}},0,0,(char *)  F_FUNC(dorgqr,DORGQR),  (f2py_init_func)f2py_rout_fpylapack_dorgqr,doc_f2py_rout_fpylapack_dorgqr},
    {"dormqr",-1,{{-1}},0,0,(char *)  F_FUNC(dormqr,DORMQR),  (f2py_init_func)f2py_rout_fpylapack_dormqr,doc_f2py_rout_fpylapack_dormqr},
    {"dtptrs",-1,{{-1}},0,0,(char *)  F_FUNC(dtptrs,DTPTRS),  (f2py_init_func)f2py_rout_fpylapack_dtptrs,doc_f2py_rout_fpylapack_dtptrs},
    {"dtrtrs",-1,{{-1}},0,0,(char *)  F_FUNC(dtrtrs,DTRTRS),  (f2py_init_func)f2py_rout_fpylapack_dtrtrs,doc_f2py_rout_fpylapack_dtrtrs},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "fpylapack",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_fpylapack(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = fpylapack_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module fpylapack (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.1.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'fpylapack' is auto-generated with f2py (version:2.1.3).\nFunctions:\n"
"    b = dgels(a,b,trans='N')\n"
"    a,jpvt,tau = dgeqp3(a)\n"
"    a = dorgqr(a,tau)\n"
"    c = dormqr(a,tau,c,side='L',trans='N')\n"
"    b = dtptrs(ap,b,uplo='U',trans='N',diag='N')\n"
"    b = dtrtrs(a,b,uplo='U',trans='N',diag='N')\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.1.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    fpylapack_error = PyErr_NewException ("fpylapack.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_fpylapack_error", fpylapack_error);
    Py_DECREF(fpylapack_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }






/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#if Py_GIL_DISABLED
    // signal whether this module supports running with the GIL disabled
    PyUnstable_Module_SetGIL(m , Py_MOD_GIL_USED);
#endif

#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"fpylapack");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
