/* File: nnls_f90module.c
 * This file is auto-generated with f2py (version:2.0.1).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Nov  4 14:37:59 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *nnls_f90_error;
static PyObject *nnls_f90_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size


#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(nnls_f90_error,errstring);\
        /*goto capi_fail;*/\
    } else 

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif


#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = nnls_f90_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = nnls_f90_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(nnls,NNLS)(double*,int*,int*,double*,double*,double*,double*,int*,int*,int*);
extern void F_FUNC(g1,G1)(double*,double*,double*,double*,double*);
extern void F_WRAPPEDFUNC(h12,H12)(int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ nnls ************************************/
static char doc_f2py_rout_nnls_f90_nnls[] = "\
nnls(a,b,x,rnorm,w,indx,mode,nsetp,[m,n])\n\nWrapper for ``nnls``.\
\n\nParameters\n----------\n"
"a : in/output rank-2 array('d') with bounds (m,n)\n"
"b : in/output rank-1 array('d') with bounds (m)\n"
"x : input rank-1 array('d') with bounds (n)\n"
"rnorm : input float\n"
"w : input rank-1 array('d') with bounds (n)\n"
"indx : input rank-1 array('i') with bounds (n)\n"
"mode : input int\n"
"nsetp : input int\n"
"\nOther Parameters\n----------------\n"
"m : input int, optional\n    Default: shape(a, 0)\n"
"n : input int, optional\n    Default: shape(a, 1)";
/* extern void F_FUNC(nnls,NNLS)(double*,int*,int*,double*,double*,double*,double*,int*,int*,int*); */
static PyObject *f2py_rout_nnls_f90_nnls(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int*,int*,double*,double*,double*,double*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *a = NULL;
    npy_intp a_Dims[2] = {-1, -1};
    const int a_Rank = 2;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    int m = 0;
    PyObject *m_capi = Py_None;
    int n = 0;
    PyObject *n_capi = Py_None;
    double *b = NULL;
    npy_intp b_Dims[1] = {-1};
    const int b_Rank = 1;
    PyArrayObject *capi_b_as_array = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    double *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    double rnorm = 0;
    PyObject *rnorm_capi = Py_None;
    double *w = NULL;
    npy_intp w_Dims[1] = {-1};
    const int w_Rank = 1;
    PyArrayObject *capi_w_as_array = NULL;
    int capi_w_intent = 0;
    PyObject *w_capi = Py_None;
    int *indx = NULL;
    npy_intp indx_Dims[1] = {-1};
    const int indx_Rank = 1;
    PyArrayObject *capi_indx_as_array = NULL;
    int capi_indx_intent = 0;
    PyObject *indx_capi = Py_None;
    int mode = 0;
    PyObject *mode_capi = Py_None;
    int nsetp = 0;
    PyObject *nsetp_capi = Py_None;
    static char *capi_kwlist[] = {"a","b","x","rnorm","w","indx","mode","nsetp","m","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOO|OO:nnls_f90.nnls",\
        capi_kwlist,&a_capi,&b_capi,&x_capi,&rnorm_capi,&w_capi,&indx_capi,&mode_capi,&nsetp_capi,&m_capi,&n_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable mode */
        f2py_success = int_from_pyobj(&mode,mode_capi,"nnls_f90.nnls() 7th argument (mode) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nsetp */
        f2py_success = int_from_pyobj(&nsetp,nsetp_capi,"nnls_f90.nnls() 8th argument (nsetp) can't be converted to int");
    if (f2py_success) {
    /* Processing variable a */
    ;
    capi_a_intent |= F2PY_INTENT_INOUT;
    const char * capi_errmess = "nnls_f90.nnls_f90.nnls: failed to create array from the 1st argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nnls_f90_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (double *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable rnorm */
        f2py_success = double_from_pyobj(&rnorm,rnorm_capi,"nnls_f90.nnls() 4th argument (rnorm) can't be converted to double");
    if (f2py_success) {
    /* Processing variable m */
    if (m_capi == Py_None) m = shape(a, 0); else
        f2py_success = int_from_pyobj(&m,m_capi,"nnls_f90.nnls() 1st keyword (m) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(a, 0) == m,"shape(a, 0) == m","1st keyword m","nnls:m=%d",m) {
    /* Processing variable n */
    if (n_capi == Py_None) n = shape(a, 1); else
        f2py_success = int_from_pyobj(&n,n_capi,"nnls_f90.nnls() 2nd keyword (n) can't be converted to int");
    if (f2py_success) {
    CHECKSCALAR(shape(a, 1) == n,"shape(a, 1) == n","2nd keyword n","nnls:n=%d",n) {
    /* Processing variable indx */
    indx_Dims[0]=n;
    capi_indx_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "nnls_f90.nnls_f90.nnls: failed to create array from the 6th argument `indx`";
    capi_indx_as_array = ndarray_from_pyobj(  NPY_INT,1,indx_Dims,indx_Rank,  capi_indx_intent,indx_capi,capi_errmess);
    if (capi_indx_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nnls_f90_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        indx = (int *)(PyArray_DATA(capi_indx_as_array));

    /* Processing variable b */
    b_Dims[0]=m;
    capi_b_intent |= F2PY_INTENT_INOUT;
    const char * capi_errmess = "nnls_f90.nnls_f90.nnls: failed to create array from the 2nd argument `b`";
    capi_b_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,b_Dims,b_Rank,  capi_b_intent,b_capi,capi_errmess);
    if (capi_b_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nnls_f90_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        b = (double *)(PyArray_DATA(capi_b_as_array));

    /* Processing variable x */
    x_Dims[0]=n;
    capi_x_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "nnls_f90.nnls_f90.nnls: failed to create array from the 3rd argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nnls_f90_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (double *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable w */
    w_Dims[0]=n;
    capi_w_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "nnls_f90.nnls_f90.nnls: failed to create array from the 5th argument `w`";
    capi_w_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,w_Dims,w_Rank,  capi_w_intent,w_capi,capi_errmess);
    if (capi_w_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nnls_f90_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        w = (double *)(PyArray_DATA(capi_w_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(a,&m,&n,b,x,&rnorm,w,indx,&mode,&nsetp);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    if((PyObject *)capi_w_as_array!=w_capi) {
        Py_XDECREF(capi_w_as_array); }
    }  /* if (capi_w_as_array == NULL) ... else of w */
    /* End of cleaning variable w */
    if((PyObject *)capi_x_as_array!=x_capi) {
        Py_XDECREF(capi_x_as_array); }
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    if((PyObject *)capi_b_as_array!=b_capi) {
        Py_XDECREF(capi_b_as_array); }
    }  /* if (capi_b_as_array == NULL) ... else of b */
    /* End of cleaning variable b */
    if((PyObject *)capi_indx_as_array!=indx_capi) {
        Py_XDECREF(capi_indx_as_array); }
    }  /* if (capi_indx_as_array == NULL) ... else of indx */
    /* End of cleaning variable indx */
    } /*CHECKSCALAR(shape(a, 1) == n)*/
    } /*if (f2py_success) of n*/
    /* End of cleaning variable n */
    } /*CHECKSCALAR(shape(a, 0) == m)*/
    } /*if (f2py_success) of m*/
    /* End of cleaning variable m */
    } /*if (f2py_success) of rnorm*/
    /* End of cleaning variable rnorm */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
    } /*if (f2py_success) of nsetp*/
    /* End of cleaning variable nsetp */
    } /*if (f2py_success) of mode*/
    /* End of cleaning variable mode */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of nnls ********************************/

/************************************* g1 *************************************/
static char doc_f2py_rout_nnls_f90_g1[] = "\
g1(a,b,cterm,sterm,sig)\n\nWrapper for ``g1``.\
\n\nParameters\n----------\n"
"a : input float\n"
"b : input float\n"
"cterm : input float\n"
"sterm : input float\n"
"sig : input float";
/* extern void F_FUNC(g1,G1)(double*,double*,double*,double*,double*); */
static PyObject *f2py_rout_nnls_f90_g1(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double a = 0;
    PyObject *a_capi = Py_None;
    double b = 0;
    PyObject *b_capi = Py_None;
    double cterm = 0;
    PyObject *cterm_capi = Py_None;
    double sterm = 0;
    PyObject *sterm_capi = Py_None;
    double sig = 0;
    PyObject *sig_capi = Py_None;
    static char *capi_kwlist[] = {"a","b","cterm","sterm","sig",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOO|:nnls_f90.g1",\
        capi_kwlist,&a_capi,&b_capi,&cterm_capi,&sterm_capi,&sig_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable a */
        f2py_success = double_from_pyobj(&a,a_capi,"nnls_f90.g1() 1st argument (a) can't be converted to double");
    if (f2py_success) {
    /* Processing variable b */
        f2py_success = double_from_pyobj(&b,b_capi,"nnls_f90.g1() 2nd argument (b) can't be converted to double");
    if (f2py_success) {
    /* Processing variable cterm */
        f2py_success = double_from_pyobj(&cterm,cterm_capi,"nnls_f90.g1() 3rd argument (cterm) can't be converted to double");
    if (f2py_success) {
    /* Processing variable sterm */
        f2py_success = double_from_pyobj(&sterm,sterm_capi,"nnls_f90.g1() 4th argument (sterm) can't be converted to double");
    if (f2py_success) {
    /* Processing variable sig */
        f2py_success = double_from_pyobj(&sig,sig_capi,"nnls_f90.g1() 5th argument (sig) can't be converted to double");
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&a,&b,&cterm,&sterm,&sig);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of sig*/
    /* End of cleaning variable sig */
    } /*if (f2py_success) of sterm*/
    /* End of cleaning variable sterm */
    } /*if (f2py_success) of cterm*/
    /* End of cleaning variable cterm */
    } /*if (f2py_success) of b*/
    /* End of cleaning variable b */
    } /*if (f2py_success) of a*/
    /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************************* end of g1 *********************************/

/************************************ h12 ************************************/
static char doc_f2py_rout_nnls_f90_h12[] = "\
h12(mode,lpivot,l1,m,u,up,c,ice,icv,ncv)\n\nWrapper for ``h12``.\
\n\nParameters\n----------\n"
"mode : input int\n"
"lpivot : input int\n"
"l1 : input int\n"
"m : input int\n"
"u : input rank-1 array('d') with bounds (f2py_u_d0)\n"
"up : input float\n"
"c : input rank-1 array('d') with bounds (f2py_c_d0)\n"
"ice : input int\n"
"icv : input int\n"
"ncv : input int";
/* extern void F_WRAPPEDFUNC(h12,H12)(int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_nnls_f90_h12(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,double*,double*,double*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int mode = 0;
    PyObject *mode_capi = Py_None;
    int lpivot = 0;
    PyObject *lpivot_capi = Py_None;
    int l1 = 0;
    PyObject *l1_capi = Py_None;
    int m = 0;
    PyObject *m_capi = Py_None;
    double *u = NULL;
    npy_intp u_Dims[1] = {-1};
    const int u_Rank = 1;
    PyArrayObject *capi_u_as_array = NULL;
    int capi_u_intent = 0;
    PyObject *u_capi = Py_None;
    double up = 0;
    PyObject *up_capi = Py_None;
    double *c = NULL;
    npy_intp c_Dims[1] = {-1};
    const int c_Rank = 1;
    PyArrayObject *capi_c_as_array = NULL;
    int capi_c_intent = 0;
    PyObject *c_capi = Py_None;
    int ice = 0;
    PyObject *ice_capi = Py_None;
    int icv = 0;
    PyObject *icv_capi = Py_None;
    int ncv = 0;
    PyObject *ncv_capi = Py_None;
    int f2py_u_d0 = 0;
    int f2py_c_d0 = 0;
    static char *capi_kwlist[] = {"mode","lpivot","l1","m","u","up","c","ice","icv","ncv",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOO|:nnls_f90.h12",\
        capi_kwlist,&mode_capi,&lpivot_capi,&l1_capi,&m_capi,&u_capi,&up_capi,&c_capi,&ice_capi,&icv_capi,&ncv_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable mode */
        f2py_success = int_from_pyobj(&mode,mode_capi,"nnls_f90.h12() 1st argument (mode) can't be converted to int");
    if (f2py_success) {
    /* Processing variable lpivot */
        f2py_success = int_from_pyobj(&lpivot,lpivot_capi,"nnls_f90.h12() 2nd argument (lpivot) can't be converted to int");
    if (f2py_success) {
    /* Processing variable l1 */
        f2py_success = int_from_pyobj(&l1,l1_capi,"nnls_f90.h12() 3rd argument (l1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable m */
        f2py_success = int_from_pyobj(&m,m_capi,"nnls_f90.h12() 4th argument (m) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ice */
        f2py_success = int_from_pyobj(&ice,ice_capi,"nnls_f90.h12() 8th argument (ice) can't be converted to int");
    if (f2py_success) {
    /* Processing variable icv */
        f2py_success = int_from_pyobj(&icv,icv_capi,"nnls_f90.h12() 9th argument (icv) can't be converted to int");
    if (f2py_success) {
    /* Processing variable ncv */
        f2py_success = int_from_pyobj(&ncv,ncv_capi,"nnls_f90.h12() 10th argument (ncv) can't be converted to int");
    if (f2py_success) {
    /* Processing variable u */
    ;
    capi_u_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "nnls_f90.nnls_f90.h12: failed to create array from the 5th argument `u`";
    capi_u_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,u_Dims,u_Rank,  capi_u_intent,u_capi,capi_errmess);
    if (capi_u_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nnls_f90_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        u = (double *)(PyArray_DATA(capi_u_as_array));

    /* Processing variable c */
    ;
    capi_c_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "nnls_f90.nnls_f90.h12: failed to create array from the 7th argument `c`";
    capi_c_as_array = ndarray_from_pyobj(  NPY_DOUBLE,1,c_Dims,c_Rank,  capi_c_intent,c_capi,capi_errmess);
    if (capi_c_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = nnls_f90_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        c = (double *)(PyArray_DATA(capi_c_as_array));

    /* Processing variable up */
        f2py_success = double_from_pyobj(&up,up_capi,"nnls_f90.h12() 6th argument (up) can't be converted to double");
    if (f2py_success) {
    /* Processing variable f2py_u_d0 */
    f2py_u_d0 = shape(u, 0);
    /* Processing variable f2py_c_d0 */
    f2py_c_d0 = shape(c, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&mode,&lpivot,&l1,&m,u,&up,c,&ice,&icv,&ncv,&f2py_u_d0,&f2py_c_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_c_d0 */
    /* End of cleaning variable f2py_u_d0 */
    } /*if (f2py_success) of up*/
    /* End of cleaning variable up */
    if((PyObject *)capi_c_as_array!=c_capi) {
        Py_XDECREF(capi_c_as_array); }
    }  /* if (capi_c_as_array == NULL) ... else of c */
    /* End of cleaning variable c */
    if((PyObject *)capi_u_as_array!=u_capi) {
        Py_XDECREF(capi_u_as_array); }
    }  /* if (capi_u_as_array == NULL) ... else of u */
    /* End of cleaning variable u */
    } /*if (f2py_success) of ncv*/
    /* End of cleaning variable ncv */
    } /*if (f2py_success) of icv*/
    /* End of cleaning variable icv */
    } /*if (f2py_success) of ice*/
    /* End of cleaning variable ice */
    } /*if (f2py_success) of m*/
    /* End of cleaning variable m */
    } /*if (f2py_success) of l1*/
    /* End of cleaning variable l1 */
    } /*if (f2py_success) of lpivot*/
    /* End of cleaning variable lpivot */
    } /*if (f2py_success) of mode*/
    /* End of cleaning variable mode */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************************* end of h12 *********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"nnls",-1,{{-1}},0,0,(char *)  F_FUNC(nnls,NNLS),  (f2py_init_func)f2py_rout_nnls_f90_nnls,doc_f2py_rout_nnls_f90_nnls},
    {"g1",-1,{{-1}},0,0,(char *)  F_FUNC(g1,G1),  (f2py_init_func)f2py_rout_nnls_f90_g1,doc_f2py_rout_nnls_f90_g1},
    {"h12",-1,{{-1}},0,0,(char *)  F_WRAPPEDFUNC(h12,H12),  (f2py_init_func)f2py_rout_nnls_f90_h12,doc_f2py_rout_nnls_f90_h12},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "nnls_f90",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_nnls_f90(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = nnls_f90_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module nnls_f90 (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'nnls_f90' is auto-generated with f2py (version:2.0.1).\nFunctions:\n"
"    nnls(a,b,x,rnorm,w,indx,mode,nsetp,m=shape(a, 0),n=shape(a, 1))\n"
"    g1(a,b,cterm,sterm,sig)\n"
"    h12(mode,lpivot,l1,m,u,up,c,ice,icv,ncv)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("2.0.1");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    nnls_f90_error = PyErr_NewException ("nnls_f90.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_nnls_f90_error", nnls_f90_error);
    Py_DECREF(nnls_f90_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }



    {
      extern void F_FUNC(h12,H12)(void);
      PyObject* o = PyDict_GetItemString(d,"h12");
      tmp = F2PyCapsule_FromVoidPtr((void*)F_FUNC(h12,H12),NULL);
      PyObject_SetAttrString(o,"_cpointer", tmp);
      Py_DECREF(tmp);
      s = PyUnicode_FromString("h12");
      PyObject_SetAttrString(o,"__name__", s);
      Py_DECREF(s);
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"nnls_f90");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
