!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2.0.1)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywraph12 (mode, lpivot, l1, m, u, up, c, ice, icv, n&
     &cv, f2py_u_d0, f2py_c_d0)
      integer mode
      integer lpivot
      integer l1
      integer m
      real(kind=8) up
      integer ice
      integer icv
      integer ncv
      integer f2py_u_d0
      integer f2py_c_d0
      real(kind=8) u(f2py_u_d0)
      real(kind=8) c(f2py_c_d0)
      interface
      
            subroutine h12(mode,lpivot,l1,m,u,up,c,ice,icv,ncv) 
                integer, intent(IN) :: mode
                integer, intent(IN) :: lpivot
                integer, intent(IN) :: l1
                integer, intent(IN) :: m
                real(kind=8), dimension(:),intent(IN OUT) :: u
                real(kind=8), intent(IN OUT) :: up
                real(kind=8), dimension(:),intent(IN OUT) :: c
                integer, intent(IN) :: ice
                integer, intent(IN) :: icv
                integer, intent(IN) :: ncv
            end subroutine h12
      end interface
      call h12(mode, lpivot, l1, m, u, up, c, ice, icv, ncv)
      end

